#!/usr/bin/env node

// Writes the open-source notices for everything the extension ships.
//
//   node scripts/notices.mjs           ->  THIRD-PARTY-NOTICES.md
//   node scripts/notices.mjs --check   ->  exits 1 if that file is out of date
//
// The bundle is minified with `--legal-comments=none`, so the licence headers
// that would normally travel with the code are stripped out of it. MIT and
// Apache-2.0 both require those notices to be carried along, which means the
// obligation has to be met somewhere else — here, in a file that ships inside
// the package and is regenerated by every build so it cannot quietly drift out
// of step with what is actually in the zip.
//
// What goes in is not a reading of package.json's dependency list, which
// includes plenty that never reaches a user. It is esbuild's own metafile —
// the exact set of files that ended up in the bundle — plus the handful of
// things vendored in whole by scripts/vendor-ocr.mjs.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(root, "THIRD-PARTY-NOTICES.md");
const META = path.join(root, ".build-meta.json");

// Copied into js/vendor/ as whole files rather than bundled, so no metafile
// knows about them. Kept in step with scripts/vendor-ocr.mjs.
const VENDORED = ["tesseract.js", "tesseract.js-core"];

// Data files, not npm packages: the trained models the OCR engine reads. They
// come from the tessdata mirror rather than node_modules, so their licence has
// to be stated by hand.
const DATA = [
  {
    name: "tessdata (eng, tur — 4.0.0 fast)",
    version: "4.0.0",
    license: "Apache-2.0",
    homepage: "https://github.com/tesseract-ocr/tessdata_fast",
    text: null, // covered by the Apache-2.0 text carried by tesseract.js-core
  },
];

/* ------------------------------------------------------- what is in the zip */

function bundledPackages() {
  if (!fs.existsSync(META)) {
    throw new Error("no .build-meta.json — run `npm run build` first, it writes one");
  }
  const meta = JSON.parse(fs.readFileSync(META, "utf8"));
  const names = new Set();
  for (const input of Object.keys(meta.inputs || {})) {
    // node_modules/@scope/name/... or node_modules/name/...
    const match = input.match(/node_modules\/((?:@[^/]+\/)?[^/]+)\//);
    if (match) names.add(match[1]);
  }
  return names;
}

/* ------------------------------------------------------ reading a package */

const LICENSE_FILES = ["LICENSE", "LICENSE.md", "LICENSE.txt", "LICENCE", "LICENCE.md", "license", "license.md"];

function readPackage(name) {
  const dir = path.join(root, "node_modules", name);
  const manifestPath = path.join(dir, "package.json");
  if (!fs.existsSync(manifestPath)) {
    throw new Error(`${name} is in the bundle but not in node_modules — run npm install`);
  }
  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));

  const file = LICENSE_FILES.map((f) => path.join(dir, f)).find((f) => fs.existsSync(f));
  if (!file) {
    throw new Error(
      `${name} ships no licence file. Read its terms and add it to this script by hand ` +
        `rather than shipping it unattributed.`
    );
  }

  return {
    name,
    version: manifest.version,
    license: manifest.license || "see below",
    homepage: manifest.homepage || `https://www.npmjs.com/package/${name}`,
    text: fs.readFileSync(file, "utf8").trim(),
  };
}

/* ------------------------------------------------------------- the document */

function render(packages) {
  // One copy of each distinct licence text, with everything it covers listed
  // above it. Forty MIT licences differing only in a copyright line is not a
  // document anybody reads; the same forty grouped by their terms is.
  const groups = new Map();
  for (const pkg of packages) {
    if (!pkg.text) continue;
    if (!groups.has(pkg.text)) groups.set(pkg.text, []);
    groups.get(pkg.text).push(pkg);
  }

  const lines = [];
  lines.push("# Third-party notices");
  lines.push("");
  lines.push(
    "Easy Note ships the open-source software listed here. Each entry keeps the",
    "licence its authors published it under; nothing below is Easy Note's own code,",
    "and nothing in Easy Note's licence overrides any of it."
  );
  lines.push("");
  lines.push(
    "This file is generated by `scripts/notices.mjs` from the build's own metafile —",
    "the exact set of sources that reached the bundle — and is rewritten by every",
    "`npm run build`. Do not edit it by hand."
  );
  lines.push("");

  lines.push("## What is in the package");
  lines.push("");
  lines.push("| Package | Version | Licence |");
  lines.push("| --- | --- | --- |");
  for (const pkg of packages) {
    lines.push(`| [${pkg.name}](${pkg.homepage}) | ${pkg.version} | ${pkg.license} |`);
  }
  lines.push("");
  if (packages.some((pkg) => !pkg.text)) {
    lines.push(
      "Entries with no licence section of their own are covered by the text of the",
      "same licence carried below by the package that ships them."
    );
    lines.push("");
  }

  let n = 0;
  for (const [text, covered] of groups) {
    n += 1;
    lines.push(`## ${n}. ${covered[0].license} — ${covered.length === 1 ? covered[0].name : `${covered.length} packages`}`);
    lines.push("");
    if (covered.length > 1) {
      for (const pkg of covered) lines.push(`- ${pkg.name} ${pkg.version}`);
      lines.push("");
    }
    lines.push("```");
    lines.push(text);
    lines.push("```");
    lines.push("");
  }

  return lines.join("\n");
}

/* -------------------------------------------------------------------- run */

const names = [...new Set([...bundledPackages(), ...VENDORED])].sort();
const packages = [...names.map(readPackage), ...DATA].sort((a, b) => a.name.localeCompare(b.name));
const document = render(packages);

if (process.argv.includes("--check")) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current !== document) {
    console.error("THIRD-PARTY-NOTICES.md is out of date — run `npm run build`");
    process.exit(1);
  }
  console.log(`  notices up to date (${packages.length} packages)`);
} else {
  fs.writeFileSync(OUT, document);
  console.log(`  THIRD-PARTY-NOTICES.md  ${packages.length} packages`);
}
